#Import Data

In [61]:
import tensorflow as tf
if tf.test.gpu_device_name():
    print('Default GPU Device: {}'.format(tf.test.gpu_device_name()))
else:
    print("Please install GPU version of TF")

Default GPU Device: /device:GPU:0


In [62]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [63]:
import pandas as pd
import numpy as np

In [64]:
#!pip install shrinemaiden

In [65]:
#from shrinemaiden.utils import trim_data
#from shrinemaiden.train import StandardTrainer


In [66]:
df = pd.read_csv('fishdata1.csv', index_col=0)  
df

Year  Month  Day  Hour  Minute  Second   PM1  PM2.5  PM10  Temp  \
S.No                                                                     
1      2019     11   26    10      27      20   8.0     12    14    25   
2      2019     11   26    10      28      12   9.0     12    15    25   
3      2019     11   26    10      29       4  10.0     14    15    26   
4      2019     11   26    10      29      56   8.0     12    12    26   
5      2019     11   26    10      30      43   9.0     12    15    26   
...     ...    ...  ...   ...     ...     ...   ...    ...   ...   ...   
23532  2019     12   10     8       8      23  18.0     27    28    45   
23533  2019     12   10     8       9       9  19.0     33    48    47   
23534  2019     12   10     8       9      57  22.0     30    34    47   
23535  2019     12   10     8      10      49  21.0     35    47    51   
23536  2019     12   10     8      11      41  23.0     34    39    47   

       Humidity  Light    CO  Water Temp    pH  
S.No                                            
1            91   34.0  95.0       24.63  6.52  
2            91   34.0  95.0       24.63  6.59  
3            89   34.0  95.0       24.63  6.53  
4            90   34.0  95.0       24.56  6.59  
5            91   34.0  95.0       24.56  6.54  
...         ...    ...   ...         ...   ...  
23532       -13   35.0  95.0       27.06  6.34  
23533         9   35.0  95.0       27.06  6.35  
23534         8   35.0  95.0       27.06  6.34  
23535         6   34.0  95.0       27.06  6.38  
23536         8   34.0  95.0       27.06  6.34  

[23536 rows x 15 columns]

In [67]:
#df = pd.read_csv('/content/drive/MyDrive/PM2.5 Project/Samut_Sakhon.txt', sep = "\t", names = ['Year', 'Month', 'Day', 'UTC Hour', 'PM2.5', 'PM10_mask', 'Retrospective'] ,header=None)
#df

In [68]:
data = df.drop(columns=['Year', 'Month', 'Day', 'Hour', 'Minute','Second'])
data=data.dropna()

In [69]:
data.columns

Index(['PM1', 'PM2.5', 'PM10', 'Temp', 'Humidity', 'Light', 'CO', 'Water Temp',
       'pH'],
      dtype='object')

#Create Model

In [70]:
# split a dataset into train and test sets
from sklearn.model_selection import train_test_split

In [71]:
#PM1
y = data['pH']
X = data[['PM1', 'PM10', 'PM2.5', 'Temp', 'Humidity', 'Light', 'CO', 'Water Temp']]

In [72]:
#turbidity
#y = data['Turbidity (0-3000 NTU)']
#X = data[['pH (0-14)', 'Temperature (ºC)', 'Turbidity (0-3000 NTU)', 'DO (0-20 mg/L)']]

In [73]:
#TDS
#y = data['TDS (0-1000 PPM)']
#X = data[['pH (0-14)', 'Temperature (ºC)', 'TDS (0-1000 PPM)', 'DO (0-20 mg/L)']]

In [74]:
# split into train test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(18060, 8) (4515, 8) (18060,) (4515,)


In [75]:
X_train.head

<bound method NDFrame.head of         PM1  PM10  PM2.5  Temp  Humidity  Light    CO  Water Temp
S.No                                                             
16088  12.0    23     18    44        -9   33.0  95.0       23.69
16373  15.0    31     25    44        10   33.0  95.0       23.69
17908  13.0    21     19    49        -1   36.0  95.0       26.56
14661  13.0    20     20    45         8   33.0  95.0       24.25
9439    7.0    13     12    46        12   39.0  95.0       28.81
...     ...   ...    ...   ...       ...    ...   ...         ...
18735  11.0    17     17    44        -1   36.0  95.0       26.13
20934  16.0    28     22    46        -5   36.0  95.0       27.25
20006  22.0    33     32    49       -13   35.0  95.0       26.31
1205    9.0    14     13    37         2   39.0  95.0       26.81
14722  12.0    20     15    42       -10   33.0  95.0       24.13

[18060 rows x 8 columns]>

In [76]:
y_train.head

<bound method NDFrame.head of S.No
16088    6.31
16373    6.33
17908    6.44
14661    6.32
9439     6.53
         ... 
18735    6.44
20934    6.40
20006    6.39
1205     6.55
14722    6.34
Name: pH, Length: 18060, dtype: float64>

In [77]:
print(f"X_train shape: {X_train.shape}")
print(f"y_train shape: {y_train.shape}")

X_train shape: (18060, 8)
y_train shape: (18060,)


In [78]:
print(X_train)

        PM1  PM10  PM2.5  Temp  Humidity  Light    CO  Water Temp
S.No                                                             
16088  12.0    23     18    44        -9   33.0  95.0       23.69
16373  15.0    31     25    44        10   33.0  95.0       23.69
17908  13.0    21     19    49        -1   36.0  95.0       26.56
14661  13.0    20     20    45         8   33.0  95.0       24.25
9439    7.0    13     12    46        12   39.0  95.0       28.81
...     ...   ...    ...   ...       ...    ...   ...         ...
18735  11.0    17     17    44        -1   36.0  95.0       26.13
20934  16.0    28     22    46        -5   36.0  95.0       27.25
20006  22.0    33     32    49       -13   35.0  95.0       26.31
1205    9.0    14     13    37         2   39.0  95.0       26.81
14722  12.0    20     15    42       -10   33.0  95.0       24.13

[18060 rows x 8 columns]


In [79]:
X_train = np.asarray(X_train)
y_train = np.asarray(y_train)
X_test = np.asarray(X_test)
y_test = np.asarray(y_test)

In [80]:
n_steps = 1
n_features = 8
b_size = 100
look_back = 1

In [81]:
def trim_data(data, batch_size):
  """
  Trims out the extra data that does not fit into batches
  EX:
  dim, batch_size = 192, 50
  to
  dim, batch_size = 150, 50

  PARAMETERS
  ----------
  data: ndarray
    The data that you want to trim
  batch_size: int
    The batch size
  """
  extra = data.shape[0] % batch_size
  if (extra == 0):
    return data
  return data[:-extra]

In [82]:
X_train = trim_data(X_train, b_size)
y_train = trim_data(y_train, b_size)
X_test  = trim_data(X_test, b_size)
y_test  = trim_data(y_test, b_size)

In [83]:
assert X_train.shape[0] == y_train.shape[0], "Train dimension mismatch"
assert X_test.shape[0] == y_test.shape[0], "Test dimension mismatch"

In [84]:
print(X_train)

[[12.   23.   18.   ... 33.   95.   23.69]
 [15.   31.   25.   ... 33.   95.   23.69]
 [13.   21.   19.   ... 36.   95.   26.56]
 ...
 [ 0.   23.   18.   ... 36.   95.   27.25]
 [14.   25.   21.   ... 36.   95.   27.19]
 [ 5.    9.    8.   ... 34.   95.   24.63]]


In [85]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(18000, 8) (4500, 8) (18000,) (4500,)


In [86]:
X_train_len = X_train.shape[0]
X_test_len = X_test.shape[0]
y_train_len = y_train.shape[0]
y_test_len = y_test.shape[0]

In [87]:
X_train = X_train.reshape(X_train_len, n_steps, n_features)
X_test  = X_test.reshape(X_test_len, n_steps, n_features)

In [88]:
print(X_train)

[[[12.   23.   18.   ... 33.   95.   23.69]]

 [[15.   31.   25.   ... 33.   95.   23.69]]

 [[13.   21.   19.   ... 36.   95.   26.56]]

 ...

 [[ 0.   23.   18.   ... 36.   95.   27.25]]

 [[14.   25.   21.   ... 36.   95.   27.19]]

 [[ 5.    9.    8.   ... 34.   95.   24.63]]]


#Apply Model

In [89]:
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf

from tensorflow.keras.models import load_model, Model 
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.models import Sequential 
from keras.layers import Dense, LSTM, Bidirectional, RepeatVector, TimeDistributed, Input, Flatten, Dropout, InputLayer
from keras.layers import LSTM, Activation
from tensorflow.keras.preprocessing.sequence import pad_sequences

from statsmodels.tools.eval_measures import rmse
from tabulate import tabulate

##List of Models

In [90]:
"""###Basic LSTM###
model = Sequential()
model.add(LSTM(200, batch_input_shape=(b_size, n_steps, n_features), name="LSTMLayer"))
model.add(Dense(1, name="OutputLayer"))
model.compile(optimizer="adam", loss="mse", metrics=['accuracy'])"""

'###Basic LSTM###\nmodel = Sequential()\nmodel.add(LSTM(200, batch_input_shape=(b_size, n_steps, n_features), name="LSTMLayer"))\nmodel.add(Dense(1, name="OutputLayer"))\nmodel.compile(optimizer="adam", loss="mse", metrics=[\'accuracy\'])'

In [91]:
"""###Stack LSTM###
model = Sequential()
model.add(LSTM(200, activation="relu", input_shape=(n_steps, n_features), return_sequences=True))
model.add(LSTM(200, activation="relu"))
model.add(Dense(1))
model.compile(optimizer="adam", loss="mse", metrics=['accuracy'])"""

'###Stack LSTM###\nmodel = Sequential()\nmodel.add(LSTM(200, activation="relu", input_shape=(n_steps, n_features), return_sequences=True))\nmodel.add(LSTM(200, activation="relu"))\nmodel.add(Dense(1))\nmodel.compile(optimizer="adam", loss="mse", metrics=[\'accuracy\'])'

In [92]:
"""###Vanilla LSTM###
model = Sequential()
model.add(LSTM(200, activation="relu", input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer="adam", loss="mse", metrics=['accuracy'])"""

'###Vanilla LSTM###\nmodel = Sequential()\nmodel.add(LSTM(200, activation="relu", input_shape=(n_steps, n_features)))\nmodel.add(Dense(1))\nmodel.compile(optimizer="adam", loss="mse", metrics=[\'accuracy\'])'

In [93]:
"""###Bidirectional LSTM###
model = Sequential()
model.add(Bidirectional(LSTM(200, activation='relu'), input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])"""

"###Bidirectional LSTM###\nmodel = Sequential()\nmodel.add(Bidirectional(LSTM(200, activation='relu'), input_shape=(n_steps, n_features)))\nmodel.add(Dense(1))\nmodel.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])"

In [94]:
"""pip install keras-self-attention"""

'pip install keras-self-attention'

In [95]:
"""pip install attention"""

'pip install attention'

In [96]:
"""
###Worst one right now###
from attention import Attention
###LSTM with Attention###
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.LSTM(200, input_shape=(n_steps, n_features),
                    return_sequences=True))
model.add(Attention(name='attention_weight'))
model.add(tf.keras.layers.Dense(1, activation='relu'))
model.compile(loss='mse', optimizer='adam', metrics=['accuracy'])  """

"\n###Worst one right now###\nfrom attention import Attention\n###LSTM with Attention###\nmodel = tf.keras.models.Sequential()\nmodel.add(tf.keras.layers.LSTM(200, input_shape=(n_steps, n_features),\n                    return_sequences=True))\nmodel.add(Attention(name='attention_weight'))\nmodel.add(tf.keras.layers.Dense(1, activation='relu'))\nmodel.compile(loss='mse', optimizer='adam', metrics=['accuracy'])  "

In [97]:
"""###GRU###Bad model
from keras.layers import GRU

model = Sequential()
model.add(GRU(200, input_shape = (n_steps, n_features), return_sequences = True))
model.add(GRU(1, return_sequences = False))
model.add(Activation('relu'))  
model.compile(loss = 'mse', optimizer = 'adam', metrics = ['accuracy'])"""

"###GRU###Bad model\nfrom keras.layers import GRU\n\nmodel = Sequential()\nmodel.add(GRU(200, input_shape = (n_steps, n_features), return_sequences = True))\nmodel.add(GRU(1, return_sequences = False))\nmodel.add(Activation('relu'))  \nmodel.compile(loss = 'mse', optimizer = 'adam', metrics = ['accuracy'])"

##compiling the model

In [98]:
#model.summary()

In [99]:
from typing import *
from sklearn.metrics import mean_squared_error
from keras.models import Sequential

import numpy as np
import tensorflow as tf
import sklearn.metrics as metrics

class StandardTrainer:
    def __init__(
        self,
        model: Sequential,
        X_train: np.ndarray,
        X_test: np.ndarray,
        y_train: np.ndarray,
        y_test: np.ndarray,
    ):
        """
        Trains the model and logs the loss, accuracy, MAE, MSE, and RMSE

        PARAMETERS
        ==========
        model: Sequential
          A Keras Sequential Model
        X_train: ndarray
          A numpy array containing the X training data
        X_test: ndarray
          A numpy array containing the X testing data
        y_train: ndarray
          A numpy array containing the y training data
        y_test: ndarray
          A numpy array containing the y testing data
        """
        self.model      = model
        self.X_train    = X_train
        self.X_test     = X_test
        self.y_train    = y_train
        self.y_test     = y_test
        self.checkpoint = None
        self.callbacks  = []

        self.checkpoint_output_file = "model_checkpoint.hdf5"
  
    def set_checkpoint(self, checkpoint: tf.keras.callbacks.ModelCheckpoint):
        """
        Sets a custom checkpoint configuration for the model.
        The default checkpoint monitors the loss, saves the weights only,
        saves the best result only, and uses the min mode.

        PARAMETERS
        ==========
        checkpoint: tf.keras.callbacks.ModelCheckpoint
          The checkpoint object
        """
        self.checkpoint = checkpoint
  
    def initialize_default_checkpoint(self):
        """
        Initializes the default checkout of the model
        """
        self.checkpoint = tf.keras.callbacks.ModelCheckpoint(
            self.checkpoint_output_file,
            monitor='loss',
            save_weights_only=True,
            save_best_only = True,
            mode = 'min'
        );
  
    def set_checkpoint_output_file(self, filename: str):
        """
        Sets the name of the output file

        PARAMETERS
        ==========
        filename: str
          The name of the file
        """
        self.checkpoint_output_file = filename

    def add_callback(self, callback):
        """
        Adds a callback to the model training process

        PARAMETERS
        ==========
        callback: A Keras Callback
          The callback of the model
        """
        self.callbacks.append(callback);
    
    def train(
        self,
        batch_size: int = 100,
        epochs: int     = 100,
        log_every: int  = 100,
        verbose: int    = 0
    ):
        """
        Trains the model

        PARAMETERS
        ==========
        batch_size: int
          DEFAULT = 1
          The batch size
        epochs: int
          DEFAULT = 1000
          The MAXIMUM epochs you want to train the model for
        log_every: int
          DEFAULT = 100
          Determines when to log the model
        verbose: int
          DEFAULT = 0
          Selects the verboseness of the training process
          0: Log only
          1: Shows Progress Bar
          2: One Line Per epoch
        """

        # Initializing the checkpoint and callback functions
        #if self.checkpoint is None:
        #  self.initialize_default_checkpoint();
        if self.checkpoint is not None:
          self.callbacks.append(self.checkpoint)

        # Training the model
        for i in range(0, epochs+1, log_every):
          print("========================================================")
          print(f"Epoch {i}-{i+log_every}:")
          hist = self.model.fit(
              self.X_train,
              self.y_train,
              batch_size = batch_size,
              epochs = log_every,
              callbacks = self.callbacks,
              verbose = verbose
          );

          # Logs the result
          prediction_result = self.model.predict(self.X_test)
          self.mae = metrics.mean_absolute_error(self.y_test, prediction_result)
          self.rms = mean_squared_error(self.y_test, prediction_result, squared=False)
          self.mse = mean_squared_error(self.y_test, prediction_result)
          self.r2 = metrics.r2_score(self.y_test, prediction_result)

          self.loss = hist.history['loss'][-1]
          self.acc  = hist.history['accuracy'][-1]

          print(f"Accuracy: {hist.history['accuracy'][-1]}")
          print(f"Loss: {hist.history['loss'][-1]}")
          print(f"MAE:{self.mae}")
          print(f"MSE:{self.mse}")
          print(f"RMSE:{self.rms}")
          print(f"R-Squared:{self.r2}")
          print("========================================================")

In [100]:
def toybox(X_train, X_test, y_train, y_test, epochs, log_every, verbose, output_csv):
  activation_list = ["relu", "sigmoid", "softmax", "softplus", "softsign",
                     "tanh", "selu", "elu"]
  optimizer_list = ["RMSprop", "Adam", "Adadelta", "Adagrad", "Adamax",
                    "Nadam", "Ftrl"] 
  # SGD CANNOT BE USED DUE TO INCOMPATIBLE DATATYPES
  # TRY IT YOURSELF

  output_file = open(output_csv, "w")

  headers = ",".join(['Optimizer','Activation Function','Activation Function 2','Epoch','Training Loss','MAE','MSE','RMSE','R-Squared'])
  headers += "\n"
  output_file.write(headers)

  output_file.close();
  
  for opt in optimizer_list:
    for act in activation_list:
      for act2 in activation_list:
        print(f"Optimizer: {opt}")
        print(f"Activation Function: {act}")
        print(f"Activation Function 2: {act2}")

        # DEFINE THE MODEL HERE
        model = Sequential()
        model.add(LSTM(200, activation=act, input_shape=(n_steps, n_features), return_sequences=True))
        model.add(LSTM(200, activation=act2))
        model.add(Dense(1))
        model.compile(optimizer = opt, loss = "mse", metrics = ['accuracy'])

        # START THE TRAINING PROCESS
        trainer = StandardTrainer (
            model = model,
            X_train = X_train,
            X_test = X_test,
            y_train = y_train,
            y_test = y_test
        )

        trainer.train (
            batch_size = b_size,
            epochs = epochs,
            log_every = log_every,
            verbose = verbose
        )

        output_str = [opt, act, act2, epochs, trainer.loss, trainer.mae, trainer.mse, trainer.rms, trainer.r2]
        output_str = [str(i) for i in output_str]
        output_str = ",".join(output_str)
        output_str += "\n"

        output_file = open(output_csv, 'a')
        output_file.write(output_str)
        output_file.close()



In [101]:
#Epochs and log_every should be the same number
toybox (
    X_train = X_train,
    X_test = X_test,
    y_train = y_train,
    y_test = y_test,
    epochs = 100,
    log_every = 100,
    verbose = 0,
    output_csv = "PH.csv"
)

Optimizer: RMSprop
Activation Function: relu
Activation Function 2: relu
Epoch 0-100:
Accuracy: 0.0
Loss: 23401406.0
MAE:840.3239015725717
MSE:21317676.722632553
RMSE:4617.106964608092
R-Squared:-0.002872855090747972
Epoch 100-200:
Accuracy: 0.0
Loss: 23405822.0
MAE:711.8191541491877
MSE:21264850.365660645
RMSE:4611.382695641368
R-Squared:-0.0003876818643326896
Optimizer: RMSprop
Activation Function: relu
Activation Function 2: sigmoid
Epoch 0-100:
Accuracy: 0.0
Loss: 23481304.0
MAE:415.79584450851524
MSE:21341972.16746417
RMSE:4619.737240088896
R-Squared:-0.004015814637466253
Epoch 100-200:
Accuracy: 0.0
Loss: 23511678.0
MAE:369.2509221282798
MSE:21370108.178569335
RMSE:4622.781433138423
R-Squared:-0.0053394505174466644
Optimizer: RMSprop
Activation Function: relu
Activation Function 2: softmax
Epoch 0-100:
Accuracy: 0.0
Loss: 23515506.0
MAE:364.10884950831183
MSE:21373362.182573352
RMSE:4623.133372786616
R-Squared:-0.005492532503276637
Epoch 100-200:
Accuracy: 0.0
Loss: 23502706.0
MA

In [102]:
"""###Convert the Result into CSV files
import csv
with open('PM2.5_activation_optimizer_Combo', 'w', newline=' ') as f
  fieldnames = ['Optimizer','Activation Function','Activation Function 2','Epoch','Training Loss','MAE','MSE','RMSE','R-Squared']
  thewriter = csv.DictWriter(f, fieldnames=fieldnames)
  thewriter.header()
  for i in range():
    thewriter.writerow({'Optimizer': opt, 'Activation Function': act,'Activation Function 2': act2,
                        'Epoch': epochs, 'Training Loss': hist.history['loss'][-1], 'MAE': mae, 'MSE': mse, 'RMSE': rms,'R-Squared': r2})"""

"###Convert the Result into CSV files\nimport csv\nwith open('PM2.5_activation_optimizer_Combo', 'w', newline=' ') as f\n  fieldnames = ['Optimizer','Activation Function','Activation Function 2','Epoch','Training Loss','MAE','MSE','RMSE','R-Squared']\n  thewriter = csv.DictWriter(f, fieldnames=fieldnames)\n  thewriter.header()\n  for i in range():\n    thewriter.writerow({'Optimizer': opt, 'Activation Function': act,'Activation Function 2': act2,\n                        'Epoch': epochs, 'Training Loss': hist.history['loss'][-1], 'MAE': mae, 'MSE': mse, 'RMSE': rms,'R-Squared': r2})"

In [103]:
from datetime import date

today = date.today()

# dd/mm/YY
d1 = today.strftime("%d/%m/%Y")
print("d1 =", d1)

# Textual month, day and year	
d2 = today.strftime("%B %d, %Y")
print("d2 =", d2)

# mm/dd/y
d3 = today.strftime("%m/%d/%y")
print("d3 =", d3)

# Month abbreviation, day and year	
d4 = today.strftime("%b-%d-%Y")
print("d4 =", d4)
import datetime
now = datetime.datetime.now()
print ("Current date and time : ")
print (now.strftime("%Y-%m-%d %H:%M:%S"))

d1 = 26/08/2022
d2 = August 26, 2022
d3 = 08/26/22
d4 = Aug-26-2022
Current date and time : 
2022-08-26 15:23:37


#ATT

In [104]:
"""trainer = StandardTrainer(
    model = model,
    X_train = X_train,
    X_test = X_test,
    y_train = y_train,
    y_test = y_test
)

#trainer.set_checkpoint_output_file("loli.hdf5")
#trainer.set_checkpoint(checkpoint)
#trainer.set_callback(callback_function)

trainer.train(
    batch_size = b_size,
    epochs = 1000,
    log_every = 100,
    verbose = 0
)"""

'trainer = StandardTrainer(\n    model = model,\n    X_train = X_train,\n    X_test = X_test,\n    y_train = y_train,\n    y_test = y_test\n)\n\n#trainer.set_checkpoint_output_file("loli.hdf5")\n#trainer.set_checkpoint(checkpoint)\n#trainer.set_callback(callback_function)\n\ntrainer.train(\n    batch_size = b_size,\n    epochs = 1000,\n    log_every = 100,\n    verbose = 0\n)'

In [105]:
"""filepath = "loli_loli_loli_trained_for_epochs.hdf5";
checkpoint = tf.keras.callbacks.ModelCheckpoint(filepath, monitor='loss', save_weights_only=True, save_best_only=True, mode='min')
model.fit(X_train, y_train, batch_size=b_size, epochs=200, callbacks=[checkpoint], verbose=1)"""

'filepath = "loli_loli_loli_trained_for_epochs.hdf5";\ncheckpoint = tf.keras.callbacks.ModelCheckpoint(filepath, monitor=\'loss\', save_weights_only=True, save_best_only=True, mode=\'min\')\nmodel.fit(X_train, y_train, batch_size=b_size, epochs=200, callbacks=[checkpoint], verbose=1)'

# Evaluating the Model

In [106]:
"""model.evaluate(X_test, y_test)"""

'model.evaluate(X_test, y_test)'

In [107]:
"""prediction_result = model.predict(X_test)"""

'prediction_result = model.predict(X_test)'

In [108]:
"""for i in range(10):
  print(f"Prediction: {prediction_result[i]} Actual Ans: {y_test[i]}")"""

'for i in range(10):\n  print(f"Prediction: {prediction_result[i]} Actual Ans: {y_test[i]}")'

In [109]:
"""import sklearn.metrics as metrics
from sklearn.metrics import mean_squared_error

mae = metrics.mean_absolute_error(y_test, prediction_result)
rms = mean_squared_error(y_test, prediction_result, squared=False)
mse = mean_squared_error(y_test, prediction_result)
r2 = metrics.r2_score(y_test, prediction_result)

print(f"MAE:{mae}")
print(f"MSE:{mse}")
print(f"RMSE:{rms}")
print(f"R-Squared:{r2}")"""

'import sklearn.metrics as metrics\nfrom sklearn.metrics import mean_squared_error\n\nmae = metrics.mean_absolute_error(y_test, prediction_result)\nrms = mean_squared_error(y_test, prediction_result, squared=False)\nmse = mean_squared_error(y_test, prediction_result)\nr2 = metrics.r2_score(y_test, prediction_result)\n\nprint(f"MAE:{mae}")\nprint(f"MSE:{mse}")\nprint(f"RMSE:{rms}")\nprint(f"R-Squared:{r2}")'